env: "develop"
product-endpoint: "http://localhost:8081"
loglevel: -4
logformat: "text"
storage:
  host: "192.168.8.242"
  port: 5556
  user: "postgres"
  password: "postgres"
  dbname: "postgres"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s