env: "local"
product-endpoint: "http://localhost:8081"
loglevel: -4
logformat: "text"
storage:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "admin"
  dbname: "postgres"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s